[package]
name = "query-search"
version = "0.1.0"
edition = "2024"
description = "High-performance search engine with inverted index"
authors = ["Kyrylo Seriuk https://github.com/Kileer20100"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/OpenQueri/query-search"
keywords = ["search", "engine", "inverted-index", "information-retrieval"]
categories = ["algorithms", "database"]

[build-dependencies]
cc = "1.2.57"

[lib]
crate-type = ["cdylib", "rlib"]
rustflags = ["-C", "target-cpu=native"]

[dependencies]
crawler-engine = { path = "../crawler-engine" }

serde = { version = "1", features = ["derive"] }
whatlang = "0.16"
libc = "0.2.183"
rayon = "1.11.0"
snowball = "0.1.3"
rustc-hash = "2.1.1"
once_cell = "1.21.4"
object-pool = "0.6.0"
tokio = { version = "1.50.0", features = ["full"] }
regex = "1.12.3"
phf = { version="0.13.1", features=["macros"]}
dashmap = { version = "6.1.0", features = ["serde"] }
indexmap = "2.13.0"
sha2 = "0.10.9"
perf-event = "0.4"
fxhash = "0.2"
bincode = "1.3"
sled = "0.34"
ort = "2.0.0-rc.12"
tokenizers = "0.19.1"
ndarray = "0.15.6"
rayon = "1.10"
candle-core = { version = "0.10.2", features = ["mkl"] }

[profile.release]
lto = "fat"      
codegen-units = 1     
panic = "abort"       
opt-level = 3
strip = true   


